/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mauricio
 */
public class IHMDesafio extends javax.swing.JFrame {
    /*Tmp = AddRoundKey (Data, Round_Key_Encrypt [0])
    For round = 1-9 or 1-11 or 1-13:
        Tmp = ShiftRows (Tmp)
        Tmp = SubBytes (Tmp)
        Tmp = MixColumns (Tmp)
        Tmp = AddRoundKey (Tmp, Round_Key_Encrypt [round])
    end loop
    Tmp = ShiftRows (Tmp)
    Tmp = SubBytes (Tmp)
    Tmp = AddRoundKey (Tmp, Round_Key_Encrypt [10 or 12 or 14])
    Result = Tmp */
    /**
     * Creates new form IHMDesafio
     */
    public IHMDesafio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        btnCrip = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCrp = new javax.swing.JTextField();
        btnDesCrp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtDesCrip = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtBoxTexto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Digite a senha de criptografia:");

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnCrip.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCrip.setText("OK");
        btnCrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCripActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Criptografado:");

        txtCrp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCrp.setEnabled(false);

        btnDesCrp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDesCrp.setText("OK");
        btnDesCrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesCrpActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Descriptografado:");

        txtDesCrip.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDesCrip.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Digite qualquer coisa:");

        txtBoxTexto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBoxTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoxTextoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtBoxTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCrip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCrp, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDesCrp)
                        .addGap(10, 10, 10)
                        .addComponent(txtDesCrip, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBoxTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesCrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesCrp))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCripActionPerformed
        try{
            String mensagem, senha;
            
            
            mensagem = txtBoxTexto.getText();
            senha = txtSenha.getText();
            
            if(senha.length() < 16){
                for(int i=0; senha.length() < 16; i++){
                    senha += senha.charAt(i);
                }
                chaveRodada.setSenhaOrg(senha.getBytes());
                chaveRodada.setRounds(senha.length());
            } else {
                chaveRodada.setSenhaOrg(senha.getBytes());
                chaveRodada.setRounds(senha.length());
            }
            byte[] mensagemByte = mensagem.getBytes();
            byte[] criptografado = new byte[mensagem.length()];
            
            /*mensagem XOR chave*/
            for(int i = 0; i < mensagem.length(); i++){
                criptografado[i] = (byte) (criptografado[i] ^ chaveRodada.RoundKeys[0][i]);
            }
            
            for(int i = 0; i < mensagem.length(); i++){
                tabela.setByteInc((byte)mensagemByte[i]);
                criptografado[i] = tabela.getByteInv();
                txtCrp.setText(String.format("0x%02X", criptografado[i]));
            }
            
            
            
            
            
            criptClass.setCript(criptografado);
            StringBuilder sb = new StringBuilder();
            for (byte b : criptografado) {
                sb.append(String.format("%02X", b)); // em hexadecimal
            }
            txtCrp.setText(sb.toString().trim());
            
            
        } catch(Exception e){ 
            
        }
    }//GEN-LAST:event_btnCripActionPerformed

    private void btnDesCrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesCrpActionPerformed
    try{    
        String  senha;
        senha = txtSenha.getText();
        byte[] senhaByte = senha.getBytes(); 
        byte[] descriptografado = new byte[criptClass.getCript().length];
        for(int i = 0; i < criptClass.getCript().length; i++){
            descriptografado[i] = (byte) (criptClass.getCript()[i] ^ senhaByte[i % senhaByte.length]);
            txtDesCrip.setText(String.format("0x%02X", descriptografado[i]));
        }
        
        for(int i = 0; i < criptClass.getCript().length; i++){
            tabela.setByteEnt(descriptografado[i]);
            descriptografado[i] = tabela.getByteOrg();
            txtDesCrip.setText(String.format("0x%02X", descriptografado[i]));
        }
        
        
        String mensagem = new String(descriptografado);
        txtDesCrip.setText(mensagem);
    } catch (Exception e){
        
    }

    }//GEN-LAST:event_btnDesCrpActionPerformed

    private void txtBoxTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoxTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoxTextoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHMDesafio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHMDesafio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHMDesafio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHMDesafio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IHMDesafio().setVisible(true);
            }
        });
    }
    private crip criptClass = new crip();
    private SBox tabela = new SBox();
    private RoundKeys chaveRodada = new RoundKeys();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrip;
    private javax.swing.JButton btnDesCrp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtBoxTexto;
    private javax.swing.JTextField txtCrp;
    private javax.swing.JTextField txtDesCrip;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
